# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build: ./mariadb
    image: taicol-mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: taicol
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/var/lib/mysql
      #- ./data:/tmp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080